version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - FAL_API_KEY=${FAL_API_KEY}
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads

volumes:
  uploads:
